version: "3.5"

services:
  # db:
  #   image: mysql:8.0
  #   command: --default-authentication-plugin=mysql_native_password
  #   container_name: dev_db
  #   environment:
  #     - MYSQL_ROOT_HOST=%
  #     - MYSQL_ROOT_PASSWORD=dev_password
  #     - MYSQL_DATABASE=dev_database
  #     - MYSQL_USER=dev_user
  #     - MYSQL_PASSWORD=dev_password
  #   ports:
  #     - 3306:3306

  api:
    build:
      context: .
    image: django_dev_api
    container_name: django_dev_api
    volumes:
      - .:/app
    env_file: .env
    ports:
      - 8080:8080
    networks:
      - default
      - jinx_network

networks:
  jinx_network:
    external: false
    name: jinx_network
