version: "3.5"

services:

  api:
    build:
      context: .
    image: django_dev_api
    container_name: django_dev_api
    volumes:
      - .:/app
    env_file: .env
    ports:
      - 8080:8080
    networks:
      - default
      - jinx_network

networks:
  jinx_network:
    external: false
    name: jinx_network
