# Generated by Django 3.2.3 on 2023-05-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='user',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], default='ADMIN', max_length=18),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddConstraint(
            model_name='onetimepassword',
            constraint=models.UniqueConstraint(fields=('email', 'password'), name='unique_email'),
        ),
        migrations.AddConstraint(
            model_name='onetimepassword',
            constraint=models.CheckConstraint(check=models.Q(('phone__isnull', False), ('email__isnull', False), _connector='OR'), name='email_phone_not_null'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
