# Generated by Django 3.2.3 on 2023-05-16 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_auto_20230512_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('user_type', models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], default='ADMIN', max_length=18)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='onetimepassword',
            name='unique_otp',
        ),
        migrations.RemoveConstraint(
            model_name='onetimepassword',
            name='email_phone_not_null',
        ),
        migrations.RemoveField(
            model_name='onetimepassword',
            name='phone',
        ),
        migrations.AddConstraint(
            model_name='onetimepassword',
            constraint=models.CheckConstraint(check=models.Q(('email__isnull', False)), name='email_not_null'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_type_mapping', to='access.usertype'),
        ),
    ]
