# Generated by Django 3.2.3 on 2023-05-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_auto_20230516_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
