# Generated by Django 3.2.3 on 2023-07-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_alter_onetimepassword_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.CharField(choices=[('USER911', 'User911'), ('FIREFIGHTER', 'Firefighter'), ('DISPATCH_CENTER', 'Dispatch Center')], max_length=18),
        ),
    ]
