# Generated by Django 3.2.3 on 2023-07-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='user_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
