# Generated by Django 3.2.3 on 2023-07-28 22:05

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_ticket_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='history',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
